//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_sinh_vien_nghien_cuu_khoa_hoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaiNCKH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetaiNCKH()
        {
            this.QuanliTHs = new HashSet<QuanliTH>();
            this.TienDoTHs = new HashSet<TienDoTH>();
        }
    
        public string Madetai { get; set; }
        public string tendetai { get; set; }
        public string noidung { get; set; }
        public Nullable<System.DateTime> ngaybd { get; set; }
        public Nullable<System.DateTime> ngaykt { get; set; }
        public string ketqua { get; set; }
        public string MaGV { get; set; }
        public string MaCN { get; set; }
        public int stt { get; set; }
    
        public virtual ChuyenNganh ChuyenNganh { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanliTH> QuanliTHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TienDoTH> TienDoTHs { get; set; }
    }
}
