//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_sinh_vien_nghien_cuu_khoa_hoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.DetaiNCKHs = new HashSet<DetaiNCKH>();
        }
    
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public string Mabomon { get; set; }
        public Nullable<System.DateTime> ngaysinhgv { get; set; }
        public Nullable<int> luong { get; set; }
        public int STT { get; set; }
        public string gioitinhGV { get; set; }
    
        public virtual BoMon BoMon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaiNCKH> DetaiNCKHs { get; set; }
    }
}
