//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_sinh_vien_nghien_cuu_khoa_hoc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class quan_li_sinh_vien_NCKHEntities : DbContext
    {
        public quan_li_sinh_vien_NCKHEntities()
            : base("name=quan_li_sinh_vien_NCKHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoMon> BoMons { get; set; }
        public virtual DbSet<ChuyenNganh> ChuyenNganhs { get; set; }
        public virtual DbSet<DetaiNCKH> DetaiNCKHs { get; set; }
        public virtual DbSet<GiaoVien> GiaoViens { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<LopSH> LopSHes { get; set; }
        public virtual DbSet<QuanliTH> QuanliTHs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Taikhoan> Taikhoans { get; set; }
        public virtual DbSet<TienDoTH> TienDoTHs { get; set; }
    
        [DbFunction("quan_li_sinh_vien_NCKHEntities", "thongtingv")]
        public virtual IQueryable<thongtingv_Result> thongtingv(string tenkhoa, string tendetai)
        {
            var tenkhoaParameter = tenkhoa != null ?
                new ObjectParameter("tenkhoa", tenkhoa) :
                new ObjectParameter("tenkhoa", typeof(string));
    
            var tendetaiParameter = tendetai != null ?
                new ObjectParameter("tendetai", tendetai) :
                new ObjectParameter("tendetai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<thongtingv_Result>("[quan_li_sinh_vien_NCKHEntities].[thongtingv](@tenkhoa, @tendetai)", tenkhoaParameter, tendetaiParameter);
        }
    
        [DbFunction("quan_li_sinh_vien_NCKHEntities", "uf_xemGV")]
        public virtual IQueryable<uf_xemGV_Result> uf_xemGV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<uf_xemGV_Result>("[quan_li_sinh_vien_NCKHEntities].[uf_xemGV]()");
        }
    
        [DbFunction("quan_li_sinh_vien_NCKHEntities", "uf_xemSV")]
        public virtual IQueryable<uf_xemSV_Result> uf_xemSV(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<uf_xemSV_Result>("[quan_li_sinh_vien_NCKHEntities].[uf_xemSV](@ma)", maParameter);
        }
    
        [DbFunction("quan_li_sinh_vien_NCKHEntities", "utf_giaovien")]
        public virtual IQueryable<utf_giaovien_Result> utf_giaovien(string mgv)
        {
            var mgvParameter = mgv != null ?
                new ObjectParameter("mgv", mgv) :
                new ObjectParameter("mgv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<utf_giaovien_Result>("[quan_li_sinh_vien_NCKHEntities].[utf_giaovien](@mgv)", mgvParameter);
        }
    
        public virtual ObjectResult<danhsachdetai_Result> danhsachdetai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<danhsachdetai_Result>("danhsachdetai");
        }
    
        public virtual ObjectResult<DanhSachGV_Result> DanhSachGV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachGV_Result>("DanhSachGV");
        }
    
        public virtual ObjectResult<DanhsachSV_Result> DanhsachSV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhsachSV_Result>("DanhsachSV");
        }
    
        public virtual ObjectResult<Nullable<int>> demsv(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("demsv", tenParameter);
        }
    
        public virtual int InsertSV(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertSV", maParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int suadetai(string tendt, string noidung, Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt, string giaovien, string chuyennganh)
        {
            var tendtParameter = tendt != null ?
                new ObjectParameter("tendt", tendt) :
                new ObjectParameter("tendt", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var giaovienParameter = giaovien != null ?
                new ObjectParameter("giaovien", giaovien) :
                new ObjectParameter("giaovien", typeof(string));
    
            var chuyennganhParameter = chuyennganh != null ?
                new ObjectParameter("chuyennganh", chuyennganh) :
                new ObjectParameter("chuyennganh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("suadetai", tendtParameter, noidungParameter, ngaybdParameter, ngayktParameter, giaovienParameter, chuyennganhParameter);
        }
    
        public virtual int Suagiaovien(string hoten, Nullable<System.DateTime> ngaysinh, string bommon, Nullable<int> luong)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var bommonParameter = bommon != null ?
                new ObjectParameter("bommon", bommon) :
                new ObjectParameter("bommon", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Suagiaovien", hotenParameter, ngaysinhParameter, bommonParameter, luongParameter);
        }
    
        public virtual int suasv(string hoten, Nullable<System.DateTime> ngaysinh, string lopsh, string diachi, string tendt, string noidung, string vaitro, string ketqua)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var lopshParameter = lopsh != null ?
                new ObjectParameter("lopsh", lopsh) :
                new ObjectParameter("lopsh", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var tendtParameter = tendt != null ?
                new ObjectParameter("tendt", tendt) :
                new ObjectParameter("tendt", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var vaitroParameter = vaitro != null ?
                new ObjectParameter("vaitro", vaitro) :
                new ObjectParameter("vaitro", typeof(string));
    
            var ketquaParameter = ketqua != null ?
                new ObjectParameter("ketqua", ketqua) :
                new ObjectParameter("ketqua", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("suasv", hotenParameter, ngaysinhParameter, lopshParameter, diachiParameter, tendtParameter, noidungParameter, vaitroParameter, ketquaParameter);
        }
    
        public virtual ObjectResult<svien_Result> svien(string dtai)
        {
            var dtaiParameter = dtai != null ?
                new ObjectParameter("dtai", dtai) :
                new ObjectParameter("dtai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<svien_Result>("svien", dtaiParameter);
        }
    
        public virtual int them_sv(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_sv", maParameter);
        }
    
        public virtual int themdetai(string ma, string ten)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themdetai", maParameter, tenParameter);
        }
    
        public virtual int ThemDT(string ma, string ten)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemDT", maParameter, tenParameter);
        }
    
        public virtual ObjectResult<themgiaovien_Result> themgiaovien(string ma, string ten)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<themgiaovien_Result>("themgiaovien", maParameter, tenParameter);
        }
    
        public virtual int themsinhvien(string ma, string ten)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themsinhvien", maParameter, tenParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> thongke(string ketqua, string ten)
        {
            var ketquaParameter = ketqua != null ?
                new ObjectParameter("ketqua", ketqua) :
                new ObjectParameter("ketqua", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("thongke", ketquaParameter, tenParameter);
        }
    
        public virtual ObjectResult<thongke_bomon_Result> thongke_bomon(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongke_bomon_Result>("thongke_bomon", tenParameter);
        }
    
        public virtual ObjectResult<thongke_sv_Result> thongke_sv(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongke_sv_Result>("thongke_sv", tenParameter);
        }
    
        public virtual ObjectResult<ThongkeSV_Result> ThongkeSV(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongkeSV_Result>("ThongkeSV", tenParameter);
        }
    
        public virtual ObjectResult<thongtin_Result> thongtin(string tenkhoa, string tendt)
        {
            var tenkhoaParameter = tenkhoa != null ?
                new ObjectParameter("tenkhoa", tenkhoa) :
                new ObjectParameter("tenkhoa", typeof(string));
    
            var tendtParameter = tendt != null ?
                new ObjectParameter("tendt", tendt) :
                new ObjectParameter("tendt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongtin_Result>("thongtin", tenkhoaParameter, tendtParameter);
        }
    
        public virtual ObjectResult<thongtin_sv_Result> thongtin_sv(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongtin_sv_Result>("thongtin_sv", tenParameter);
        }
    
        public virtual ObjectResult<Thongtinbm_Result> Thongtinbm(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Thongtinbm_Result>("Thongtinbm", tenParameter);
        }
    
        public virtual ObjectResult<timkiemdetai_Result> timkiemdetai(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timkiemdetai_Result>("timkiemdetai", tenParameter);
        }
    
        public virtual ObjectResult<TimkiemGV_Result> TimkiemGV(string tengv)
        {
            var tengvParameter = tengv != null ?
                new ObjectParameter("tengv", tengv) :
                new ObjectParameter("tengv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimkiemGV_Result>("TimkiemGV", tengvParameter);
        }
    
        public virtual ObjectResult<TimkiemSV_Result> TimkiemSV(string tensv)
        {
            var tensvParameter = tensv != null ?
                new ObjectParameter("tensv", tensv) :
                new ObjectParameter("tensv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimkiemSV_Result>("TimkiemSV", tensvParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TK(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TK", tenParameter);
        }
    
        public virtual int xoadetai(string tendt)
        {
            var tendtParameter = tendt != null ?
                new ObjectParameter("tendt", tendt) :
                new ObjectParameter("tendt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoadetai", tendtParameter);
        }
    
        public virtual int xoagiaovien(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoagiaovien", maParameter);
        }
    
        public virtual int XoaSV1(string hoten)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaSV1", hotenParameter);
        }
    }
}
