//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_sinh_vien_nghien_cuu_khoa_hoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.QuanliTHs = new HashSet<QuanliTH>();
        }
    
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Diachi { get; set; }
        public string MalopSH { get; set; }
        public Nullable<int> tongsodetai { get; set; }
        public int STT { get; set; }
        public string gioitinh { get; set; }
    
        public virtual LopSH LopSH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanliTH> QuanliTHs { get; set; }
    }
}
