//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_sinh_vien_nghien_cuu_khoa_hoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TienDoTH
    {
        public string MaTD { get; set; }
        public Nullable<int> ketquaTD { get; set; }
        public string Madetai { get; set; }
    
        public virtual DetaiNCKH DetaiNCKH { get; set; }
    }
}
